### PR TITLE
Updates test data and config, adds docs, moves data to lifebit s3

### LINKED ISSUE #24: Move all reference data to lifebit s3 bucket

### LINKED ISSUE #26: Add complete documentation on how to run the pipeline on CloudOS
Should include instruction on how to install nextflow and docker for brand new users (not for cloudos though)

Should have example command to run pipeline with no prior knowledge with public test data file, possbily with "-profile test", and then also with detailed command line args

Should have dertailed explanation of input and output files

### PR DESCRIPTION
**Pull request by Vlad-Dembrovskyi**
## Description
This PR closes #24 , closes #26 .

- [x] updates test config, test csv file, uploads test data to lifebit's s3 bucket:
image
- [x] upload pcgr reference data to lifebit's s3 bucket:
image
- [x] adds documentation on how to run the pipeline on CloudOS: [docs/usage_cloudos.md](https://github.com/lifebit-ai/pcgr-nf/blob/upd-test-and-docs/docs/usage_cloudos.md)

## Testing

To test the pipeline with new test and reference data locally run:
```
git clone https://github.com/lifebit-ai/pcgr-nf
cd pcgr-nf
git checkout upd-test-and-docs
NXF_VER=20.01.0 nextflow run . -profile standard,docker --config conf/test.config
```
This will take 16-20 minutes because it needs to stage the pcgr reference data first (which I suggest to improve in #36 )
image
image

## CloudOS run
https://cloudos.lifebit.ai/public/jobs/611a2c927db707019a066cbf
https://cloudos.lifebit.ai/app/jobs/611a2c927db707019a066cbf
image
image
image

### CODE REVIEW

**Comment by Vlad-Dembrovskyi** [comment]
image

**Comment by imendes93** [comment]
Hello! Tested the PR locally with the provided command on my M1 machine:
`NXF_VER=20.01.0 nextflow run . -profile standard,docker --config conf/test.config
`
Unfortunately this is failing for me with the following error : 
image
image

I've tried running it again without using the test.config file and i've managed to run it successfully:
image

On cloudOS I tested with (https://cloudos.lifebit.ai/public/jobs/611cda087db707019a08be4f) and without (https://cloudos.lifebit.ai/public/jobs/611cd3ec7db707019a08bc5e) the config file as parameter. With the config file on cloudOS the last process failed for me using the commit id https://github.com/lifebit-ai/pcgr-nf/commit/87283b72ded768b847061ee354ed4371cdf00634 

I'm running it again to see if I can reproduce the error.

**Comment by imendes93** [comment]
I've added minor improvements to the documentation, including the README and how to run in CloudOS. I've retested running the workflow on cloudOS (same commit id as before) and this time it worked without any issue using the config file option:
https://cloudos.lifebit.ai/public/jobs/611ce1c17db707019a08c069
image
image

I don't know what the consistent behaviour was due to, but I'm happy to be able to test it on CloudOS and have both versions (parameters and config file working).

Currently waiting on feedback from @cgpu on running locally with the config file to approve and merge this PR

**Comment by cgpu** [comment]
> I've added minor improvements to the documentation, including the README and how to run in CloudOS. I've retested running the workflow on cloudOS (same commit id as before) and this time it worked without any issue using the config file option:
> https://cloudos.lifebit.ai/public/jobs/611ce1c17db707019a08c069
> image
> image
> 
> I don't know what the consistent behaviour was due to, but I'm happy to be able to test it on CloudOS and have both versions (parameters and config file working).
> 
> Currently waiting on feedback from @cgpu on running locally with the config file to approve and merge this PR

It works for me (machine with Intel chip and not M1) as expected, and since it works in CloudOS as well I am happy for this to be merged. We can take the M1 chip troubleshooting internally and brainstorm on the solution.


image

**Review by cgpu — APPROVED** [review]

**Pull request merged**
